BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Menu] ADD [serviceCost] FLOAT(53) NOT NULL CONSTRAINT [Menu_serviceCost_df] DEFAULT 0.0,
[tips] FLOAT(53),
[total] FLOAT(53) NOT NULL CONSTRAINT [Menu_total_df] DEFAULT 0.0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
